version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "18977:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - streamlit
    networks:
      - streamlit_net

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8501"
    networks:
      - streamlit_net

networks:
  streamlit_net: